// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTrToE3QDaQx3lpXd3yUI0C9-Mvlzku6o',
    appId: '1:861852771839:web:19c5a2ad582917af2133ca',
    messagingSenderId: '861852771839',
    projectId: 'basisdata-3f324',
    authDomain: 'basisdata-3f324.firebaseapp.com',
    databaseURL: 'https://basisdata-3f324.firebaseio.com',
    storageBucket: 'basisdata-3f324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7QjcNupcB-N76F3ff49Pnzo0TfEWd3cM',
    appId: '1:861852771839:android:fbb3b21953e3fb982133ca',
    messagingSenderId: '861852771839',
    projectId: 'basisdata-3f324',
    databaseURL: 'https://basisdata-3f324.firebaseio.com',
    storageBucket: 'basisdata-3f324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv1Tr-q5EpxKbW7edcsaO6zs2dJDLMfzQ',
    appId: '1:861852771839:ios:b8b9c9f231ef75d92133ca',
    messagingSenderId: '861852771839',
    projectId: 'basisdata-3f324',
    databaseURL: 'https://basisdata-3f324.firebaseio.com',
    storageBucket: 'basisdata-3f324.appspot.com',
    androidClientId: '861852771839-amjsr3o85v2u1tp402k3o55c9ods3pv8.apps.googleusercontent.com',
    iosClientId: '861852771839-jfso7ctrnd6la0i20oid5o7m5jh3a4ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv1Tr-q5EpxKbW7edcsaO6zs2dJDLMfzQ',
    appId: '1:861852771839:ios:b8b9c9f231ef75d92133ca',
    messagingSenderId: '861852771839',
    projectId: 'basisdata-3f324',
    databaseURL: 'https://basisdata-3f324.firebaseio.com',
    storageBucket: 'basisdata-3f324.appspot.com',
    androidClientId: '861852771839-amjsr3o85v2u1tp402k3o55c9ods3pv8.apps.googleusercontent.com',
    iosClientId: '861852771839-jfso7ctrnd6la0i20oid5o7m5jh3a4ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
